declare const PUBLICPATH = '/mynotes-es'
declare const DRACOPATH = '/mynotes-es/resource/three/gltf/'
declare const MODELSRESOURCEPATH = '/mynotes-es/resource/three/models'
declare const ONIGASMPATH = '/mynotes-es/resource/onigasm'
declare const MDXPATH = '/mynotes-es/resource/mdx'
