name: mynote-es
 on:
   push:
     branches:
       - main

 # 任务
 jobs:
   build-and-deploy:
     # 服务器环境：最新版 Ubuntu
     runs-on: ubuntu-latest
     steps:
       # 拉取代码
       - name: Checkout
         uses: actions/checkout@v3
         with:
           persist-credentials: false
       # 生成静态文件
       - name: Build
         run: |
           npm install  # 安装依赖
           npm run build  # 执行打包

       # 部署到 GitHub Pages
       - name: Deploy
         uses: JamesIves/github-pages-deploy-action@v4.3.3
         with:
           ACCESS_TOKEN: ${{ secrets.MYNOTE_ES }} # 也就是我们刚才生成的 secret
           bravch: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
           folder: dist # 生成的静态文件存放的地方
